[package]
name = "rust-hello-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
tokio = { version = "1.32.0", features = ["full"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
env_logger = "0.10.0"
dotenv = "0.15.0"
config = "0.13.3"