[package]
name = "rust-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
tokio = { version = "1.28.0", features = ["full"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
env_logger = "0.10.0"
log = "0.4.17"
dotenv = "0.15.0"

[dev-dependencies]
actix-rt = "2.8.0"
reqwest = { version = "0.11.18", features = ["json"] }
tokio-test = "0.4.2"
