//! Fibonacci sequence generator.

pub struct Fibonacci {
    a: u64,
    b: u64,
}

impl Fibonacci {
    pub fn new() -> Self {
        Fibonacci {
            a: 0,
            b: 1,
        }
    }
}

impl Iterator for Fibonacci {
    type Item = u64;

    /// Generates the next Fibonacci number.
    ///
    /// The sequence starts with 0 and 1. Subsequent numbers are generated by summing the previous two.
    /// There is no explicit limit to the sequence, but the `u64` type limits the maximum Fibonacci number that can be represented.
    fn next(&mut self) -> Option<Self::Item> {
        let next = self.a.wrapping_add(self.b);
        let current = self.a;
        self.a = self.b;
        self.b = next;
        Some(current)
    }
}
