ame: CI

on:
  push:
    branches: [main]
  pull_request:
    # This triggers on all pull requests

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --verbose

      # Placeholder steps for future tasks
      - name: Run tests
        run: cargo test --verbose

      - name: Run quality checks (placeholder)
        run: echo "Quality checks (linting, formatting) will run here later"